FROM ruby:2.6.2-slim

RUN apt-get update && apt-get install -qq -y --no-install-recommends \
      build-essential nodejs libpq-dev cron

RUN touch /var/log/cron.log
ENV INSTALL_PATH /expensescontrol
ENV RAILS_ENV production
RUN mkdir -p $INSTALL_PATH
WORKDIR $INSTALL_PATH
ADD Gemfile $INSTALL_PATH/Gemfile
ADD Gemfile.lock $INSTALL_PATH/Gemfile.lock
RUN bundle install --without test, development
ADD . $INSTALL_PATH
CMD ['bundle', 'exec', 'puma']
